database:
  connection_string: ${DATABASE_URL}
  pool_size: 10
embeddings:
  model: sentence-transformers/all-MiniLM-L6-v2
  batch_size: 32
cache:
  ttl_seconds: 300
  max_size: 1000
storage:
  base_dir: ./data
  chroma_dir: ./data/chroma
logging:
  level: INFO
  json: true
server:
  host: 0.0.0.0
  port: 8000
  workers: 1
