version: '3.8'
services:
  backend:
    image: python:3.11-slim
    working_dir: /app
    volumes:
      - ./:/app
    environment:
      - PYTHONUNBUFFERED=1
      - PIP_NO_CACHE_DIR=1
      - DATABASE_URL=
    ports:
      - "8000:8000"
    command: sh -c "pip install --upgrade pip && pip install -r requirements.txt && uvicorn backend.main:app --host 0.0.0.0 --port 8000"
